### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by lizhe-951202** [JeremyOng96/A-Hybrid-Method-for-Pavement-Crack-Width-Measurement#1]
When I run measurement_methods.py, I got the error: **ValueError: attempt to get argmin of an empty sequence**

What revision should I do for the relevant file?

Help, please……

**Comment by JeremyOng96** [comment]
Hi, this is because the algorithm needs two points that are on opposing boundaries to calculate the distance. For example, if the two points are lying on the same side, there will be no points in one candidate group. Based on our crack testings, our simple radius function works okay, this function depends on your use case. However, a simple fix would be in the measurement_methods.py line 195. You will need to find a suitable equation that encapsulates two sides of the boundary so that the distance can be calculated. If not, there will be no distance to be calculated. This problem is due to the MAT being very close to the boundaries, giving you 0 distance. Therefore, maybe you can add a constant to the radius so that this problem will not appear for your use case.

For example, you can try to replace the radius function in line 195 with the following:
radius = dt[r_p,c_p]*2+(insert your own constant)

**Comment by JeremyOng96** [comment]
> 
Hi, the algorithm needs two points on opposing boundaries to calculate the distance. For example, if the two points lie on the same side, there will be no points in one of the candidate groups. Based on our crack testings, our simple radius function works okay. A simple fix would be in the measurement_methods.py line 195. You will need to find a suitable equation that encapsulates two sides of the boundary so that the distance can be calculated. If not, there will be no distance to be calculated. This problem is due to the MAT being very close to the boundaries, giving you 0 distance.
